### ISSUE TITLE
Unexpected token when using @testing-library/svelte

### ISSUE THREAD

**Issue by samedro** [EmilTholin/svelte-routing#140]
Hi,

I'm new to svelte, and I'm trying to add some unit tests to my application. I followed explanations on how to setup the testing library, but when I execute the "npm test" command on a component that imports for exemple : ```import { link } from 'svelte-routing';```, there is this error : 
```
 Jest encountered an unexpected token

 Details:

 ~pathToMyProject/node_modules/svelte-routing/src/index.js:1
 export { default as Router } from "./Router.svelte";
 ^^^^^^

 SyntaxError: Unexpected token export
```

Could someone help me on this one ?

Thanks.

**Comment by EmilTholin** [comment]
Hi @samedro!

It's difficult to say what might have gone wrong with your test setup without seeing your project. Could you share a minimal reproducible example that we can ideally clone and try?

The issue is that your code has not been transpiled before testing and Jest doesn't know what to do with the `export` keyword.

**Comment by user896724** [comment]
I'm also getting this issue with SSR.  Does the code need to be transpiled for SSR?

**Comment by blacksonic** [comment]
@EmilTholin the problem is Babel setups doesn't transpile files within `node_modules`. There is no build of the library for good old CommonJS.

**Comment by blacksonic** [comment]
There is no build step before publishing, just the raw svelte and es6 syntax files.

**Comment by agrawal-rohit** [comment]
I was able to get past this error by adding a **transformIgnorePatterns** in my jest.config.js

**_jest.config.js_**
```
module.exports = {
    transform: {
      '^.+\\.svelte$': 'svelte-jester',
      '^.+\\.js$': 'babel-jest',
    },
    transformIgnorePatterns: [
        "node_modules/?!(svelte-routing)"
      ],
    moduleFileExtensions: ['js', 'svelte'],
  }
```

_**babel.config.js**_
```
module.exports = {
    presets: [
      [
        '@babel/preset-env',
        {
          targets: {
            node: 'current',
          },
        },
      ],
    ],
  }
```

**However**, this led to another error from `Link.svelte` as follows:
```
TypeError: Cannot destructure property 'base' of 'getContext(...)' as it is undefined.
```
I came across [this thread](https://gitmemory.com/issue/EmilTholin/svelte-routing/57/507040166) while looking for a solution but haven't been able to solve it.

**Comment by nhe23** [comment]
@agrawal-rohit Having the same issue:
 
`TypeError: Cannot destructure property 'base' of 'undefined' or 'null'.`

      at instance (node_modules/svelte-routing/src/Link.svelte:105:8)
      at init (node_modules/svelte/internal/index.js:1474:11)
      at new Link (node_modules/svelte-routing/src/Link.svelte:236:3)
      at create_fragment (src/components/Nav/Nav.svelte:207:9)
      at init (node_modules/svelte/internal/index.js:1489:37)
      at new Nav (src/components/Nav/Nav.svelte:389:3)
      at Object.render (node_modules/@testing-library/svelte/dist/pure.js:81:21)
      at Object.<anonymous> (src/components/Nav/Nav.spec.ts:5:27)`

Have you found a solution?

**Comment by anthonytranDev** [comment]
## Problem

`Link.js`
```js
...
const { base } = getContext(ROUTER); // <-- Here
const location = getContext(LOCATION); // <-- Issue will affect this context as well !
const dispatch = createEventDispatcher();
...
```

`Router`
```js
...
  setContext(ROUTER, {
    activeRoute,
    base,
    routerBase,
    registerRoute,
    unregisterRoute
  });
</script>
...
```

In the Link component `ROUTER` given to `getContext(ROUTER)`, will be default assigned to `undefined`, as `setContext` from the `Router.js` component has not been used pass down the context object `ROUTER` to `getContext(ROUTER)`

```TypeError: Cannot destructure property 'base' of 'getContext(...)' as it is undefined.```

Hence you'll need to configure your tests to pass down a `Router` or `MockRouter` component, during your `Jest`, including `@testing-library/svelte` tests

## Workaround
It's not a nice workaround, as I'm currently using a package to convert my test files from `*.js` to `*.jsx` solely to enable me to easily test components that are nested (same as I would in React). 😢 

1. Install the following `npm install --save-dev svelte-jsx @babel/plugin-transform-react-jsx`
2. Read instructions in `svelte-jsx` on how to test nested components - https://github.com/kenoxa/svelte-jsx#babel-configuration

You'd expect something like;

```jsx
render(
  <Router>
    <Link to="/"></Link>
  </Router>,
)
```
