### ISSUE TITLE
when i run the example ,an error occurred!

### ISSUE THREAD

**Issue by xiatian12345** [EmilTholin/svelte-routing#248]
I follow the step:

1. git clone git@github.com:EmilTholin/svelte-routing.git
2. cd svelte-routing/example
3. npm install
4. npm start
5. open http://localhost:3000

And then i got the error :

```
TypeError: c is not a function
    at /Users/xiatian/Desktop/ttt/svelte-routing/example/public/App.js:653:76
    at Object.$$render (/Users/xiatian/Desktop/ttt/svelte-routing/example/public/App.js:281:22)
    at Object.default (/Users/xiatian/Desktop/ttt/svelte-routing/example/public/App.js:1147:46)
    at /Users/xiatian/Desktop/ttt/svelte-routing/example/public/App.js:1011:17
    at Object.$$render (/Users/xiatian/Desktop/ttt/svelte-routing/example/public/App.js:281:22)
    at /Users/xiatian/Desktop/ttt/svelte-routing/example/public/App.js:1128:49
    at $$render (/Users/xiatian/Desktop/ttt/svelte-routing/example/public/App.js:281:22)
    at Object.render (/Users/xiatian/Desktop/ttt/svelte-routing/example/public/App.js:289:26)
    at /Users/xiatian/Desktop/ttt/svelte-routing/example/server.js:10:26
    at Layer.handle [as handle_request] (/Users/xiatian/Desktop/ttt/svelte-routing/example/node_modules/express/lib/router/layer.js:95:5)
```

Then i upgrade the svelte-routing version to 1.11.0,but the error still exist.

**Comment by krishnaTORQUE** [comment]
Sorry
The example is very old & does not gonna work.

**Comment by krishnaTORQUE** [comment]
Example will not work because it is too old.
There are so many things has been changed.
Example will be removed in next push.
