### ISSUE TITLE
 c is not a function

### ISSUE THREAD

**Issue by rushirufu** [EmilTholin/svelte-routing#295]
index.astro
```js
---
import Layout from "../layouts/Layout.astro";
import ABC from "@/components/Routers.svelte";
---

<Layout title="Welcome to Astro.">
  <ABC client:load />
</Layout>
```

rounters.svelte
```js
<!-- ROUTERS.svelte -->
<script>
  import { Router, Link, Route } from "svelte-routing";
  import A from "@/components/A.svelte";
  import B from "@/components/B.svelte";
  import C from "@/components/C.svelte";
  export let url = "";
</script>

<Router {url}>
  <nav>
    <Link to="/">A</Link>
    <Link to="/b">B</Link>
    <Link to="/c">C</Link>
  </nav>
  <div>
    <Route path="/b" component={B} />
    <Route path="/c" component={C} />
    <Route path="/" component={A} />
  </div>
</Router>
```

**Error:** output
c is not a function

```js
<script>
    import { getContext, onDestroy } from "svelte";
    import { ROUTER } from "./contexts.js";
    import { canUseDOM } from "./utils.js";

    export let path = "";
    export let component = null;

    let routeParams = {};
    let routeProps = {};

    const { registerRoute, unregisterRoute, activeRoute } = getContext(ROUTER);

    const route = {
        path,
        // If no path prop is given, this Route will act as the default Route
        // that is rendered if no other Route in the Router is a match.
        default: path === "",
    };

    $: if ($activeRoute && $activeRoute.route === route) {
        routeParams = $activeRoute.params;

        const { component: c, path, ...rest } = $$props;
        routeProps = rest;

        if (c) {
            if (c.toString().startsWith("class ")) component = c;
            else component = c();
        }

        canUseDOM() && !$activeRoute.preserveScroll && window?.scrollTo(0, 0);
    }

    registerRoute(route);

    onDestroy(() => {
        unregisterRoute(route);
    });
</script>

{#if $activeRoute && $activeRoute.route === route}
    {#if component}
        {#await component then resolvedComponent}
            <svelte:component
                this={resolvedComponent?.default || resolvedComponent}
                {...routeParams}
                {...routeProps}
            />
        {/await}
    {:else}
        <slot params={routeParams} />
    {/if}
{/if}
```

TypeError: c is not a function
    at C:\GitHub\crm-goc\frontend\node_modules\svelte-routing\src\Route.svelte:29:30
    at Object.$$render (C:\GitHub\crm-goc\frontend\node_modules\svelte\src\runtime\internal\ssr.js:156:16)
    at Object.default (C:/GitHub/crm-goc/frontend/src/components/Routers.svelte:34:434)
    at eval (C:/GitHub/crm-goc/frontend/node_modules/svelte-routing/src/Router.svelte:167:18)
    at Object.$$render (C:\GitHub\crm-goc\frontend\node_modules\svelte\src\runtime\internal\ssr.js:156:16)
    at eval (C:/GitHub/crm-goc/frontend/src/components/Routers.svelte:20:95)
    at $$render (C:\GitHub\crm-goc\frontend\node_modules\svelte\src\runtime\internal\ssr.js:156:16)
    at Object.render (C:\GitHub\crm-goc\frontend\node_modules\svelte\src\runtime\internal\ssr.js:164:17)
    at Object.renderToStaticMarkup (C:\GitHub\crm-goc\frontend\node_modules\@astrojs\svelte\server.js:17:29)
    at renderFrameworkComponent (C:\GitHub\crm-goc\frontend\node_modules\astro\dist\runtime\server\render\component.js:222:66)

package.json
```json
{
  "name": "frontend",
  "type": "module",
  "version": "0.0.1",
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro check && astro build",
    "preview": "astro preview",
    "astro": "astro"
  },
  "dependencies": {
    "@astrojs/check": "^0.5.10",
    "@astrojs/svelte": "^5.4.0",
    "@astrojs/tailwind": "^5.1.0",
    "astro": "^4.6.3",
    "svelte": "^4.2.15",
    "svelte-routing": "^2.13.0",
    "tailwindcss": "^3.4.3",
    "typescript": "^5.4.5"
  },
  "devDependencies": {
    "@iconify/svelte": "^4.0.2"
  }
}
```

**Comment by rushirufu** [comment]
solution:

```js
<!-- ROUTERS.svelte -->
<script>
  import { Router, Link, Route } from "svelte-routing";
  import A from "@/components/A.svelte";
  import B from "@/components/B.svelte";
  import C from "@/components/C.svelte";
  export let url = "";
  let basepath = "admin";
</script>

<Router {url}>
  <nav>
    <Link to="/">A</Link>
    <Link to="/b">B</Link>
    <Link to="/c">C</Link>
  </nav>
  <div>
    <Route path="b" component={B} />
    <Route path="c" component={C} />
    <Route path="a" component={A} />
  </div>
</Router>
```
